# Coast Range Forestry Management Study Area
# Focus on sustainable timber management and ecosystem services

name: coast_range_forestry
description: >
  Coast Range forest management area spanning Oregon and Northern California.
  Focuses on sustainable timber harvesting, old-growth conservation, salmon habitat
  protection, and carbon sequestration in mixed conifer and hardwood forests.

# Geographic Bounds Configuration
geographic_bounds:
  bounds_type: bbox
  definition:
    north: 46.0   # Northern Oregon Coast Range
    south: 40.0   # Northern California coastal forests (Humboldt/Mendocino)
    west: -124.5  # Pacific Coast
    east: -122.8  # Eastern edge of Coast Range
  buffer_km: 2.0
  crs: EPSG:4326

# Bioregional Context
bioregional_context:
  bioregion_type: forestry
  primary_ecosystem: conifer_forest
  management_focus:
    - timber
    - carbon
    - biodiversity
    - water
  climate_zone: temperate_oceanic
  conservation_priority: high
  
  # Forestry characteristics
  forest_type: mixed  # Old-growth, second-growth, and some plantation
  timber_management: sustainable
  
  # Some agricultural interface
  primary_crops: []  # Minimal agriculture
  farming_type: null
  water_source: rainfed

# Resolution Rules (forest management complexity-based)
resolution_rules:
  - name: old_growth_conservation
    condition: "building_volume < 50 and FSI_24 < 0.01"
    resolution: 10
    priority: 100
    description: "Old-growth and high-conservation value forests"
    
  - name: active_timber_management
    condition: "FSI_24 >= 0.01 and FSI_24 < 0.05 and building_volume >= 50"
    resolution: 9  
    priority: 95
    description: "Active timber management areas with infrastructure"
    
  - name: riparian_forest_buffers
    condition: "FSI_24 < 0.02 and building_volume < 100"
    resolution: 10
    priority: 90
    description: "Stream corridors and riparian forest buffers"
    
  - name: forest_roads_clearings
    condition: "FSI_24 >= 0.02 and FSI_24 < 0.1"
    resolution: 9
    priority: 85
    description: "Forest roads, clearings, and management infrastructure"
    
  - name: regenerating_forests
    condition: "FSI_24 < 0.005"
    resolution: 8
    priority: 80
    description: "Young regenerating forests and low-impact areas"

# Default resolution
default_resolution: 8

# Density Filtering Configuration
density_filtering:
  enable: true
  method: fsi_threshold  
  min_fsi_threshold: 0.001  # Include even very low-density forest areas
  exclude_water_bodies: false  # Include streams and wetlands
  exclude_steep_slopes: false  # Include steep forested slopes

# Bioregional Filtering Configuration
bioregional_filtering:
  enable_ecosystem_rules: true
  prioritize_conservation_zones: true
  include_riparian_buffers: true
  riparian_buffer_meters: 200  # Wider buffers for salmon habitat
  forest_edge_buffer_meters: 100
  
  # Forest-specific filtering
  old_growth_priority: high
  timber_harvest_monitoring: true
  carbon_sequestration_focus: true

# Computational Constraints
max_memory_gb: 18.0  # Higher memory for detailed forest analysis
max_hexagons_per_chunk: 40000  # Smaller chunks due to high resolution requirements
enable_chunking: true

# Quality Thresholds
min_coverage_threshold: 0.9   # Very high coverage for forest monitoring
min_density_threshold: 0.001  # Include very sparse forest infrastructure