# Eastern Oregon Rangelands Study Area  
# Focus on extensive grazing systems and drought resilience

name: eastern_oregon_rangelands
description: >
  Eastern Oregon rangeland systems focusing on sustainable grazing management,
  drought adaptation, and regenerative rangeland practices. Covers extensive
  semi-arid grasslands and sagebrush ecosystems with scattered agricultural development.

# Geographic Bounds Configuration
geographic_bounds:
  bounds_type: counties
  definition:
    - Malheur
    - Harney  
    - Lake
    - Grant
  buffer_km: 0.0
  crs: EPSG:4326

# Bioregional Context
bioregional_context:
  bioregion_type: mixed_use
  primary_ecosystem: grassland
  management_focus:
    - grazing
    - drought_resilience
    - carbon
    - biodiversity
  climate_zone: semi_arid
  conservation_priority: standard
  
  # Agricultural characteristics
  primary_crops:
    - hay
    - barley
    - pasture
  farming_type: conventional
  water_source: mixed  # Some irrigated valleys, mostly dryland
  
  # Rangeland characteristics
  forest_type: null  # Minimal forest cover
  timber_management: null

# Resolution Rules (optimized for computational efficiency in sparse areas)
resolution_rules:
  - name: irrigated_valley_agriculture
    condition: "FSI_24 >= 0.1"
    resolution: 9
    priority: 100
    description: "Irrigated agricultural valleys (detailed for water use analysis)"
    
  - name: ranch_headquarters
    condition: "building_volume >= 500 and FSI_24 >= 0.02"
    resolution: 9
    priority: 95
    description: "Ranch headquarters and agricultural facilities"
    
  - name: riparian_grazing_areas
    condition: "FSI_24 >= 0.005 and FSI_24 < 0.05 and building_volume < 200"
    resolution: 9
    priority: 90
    description: "Riparian areas and intensive grazing zones"
    
  - name: extensive_rangeland
    condition: "FSI_24 >= 0.001 and FSI_24 < 0.01"
    resolution: 8
    priority: 80
    description: "Extensive rangeland with minimal infrastructure"
    
  - name: wilderness_minimal_impact
    condition: "FSI_24 < 0.001"
    resolution: 7
    priority: 70
    description: "Wilderness and very low-impact rangeland (coarse resolution for efficiency)"

# Default resolution (optimized for computational efficiency)
default_resolution: 8

# Density Filtering Configuration
density_filtering:
  enable: true
  method: fsi_threshold
  min_fsi_threshold: 0.0005  # Very low threshold to capture sparse rangeland use
  exclude_water_bodies: false  # Include water sources critical for grazing
  focus_on_grazing_infrastructure: true

# Bioregional Filtering Configuration  
bioregional_filtering:
  enable_ecosystem_rules: true
  prioritize_water_sources: true
  include_riparian_buffers: true
  riparian_buffer_meters: 200
  
  # Rangeland-specific filtering
  grazing_management_focus: true
  drought_monitoring_priority: high
  carbon_sequestration_potential: true
  minimal_infrastructure_areas: true

# Computational Constraints (optimized for large sparse areas)
max_memory_gb: 10.0  # Lower memory requirement due to sparse data
max_hexagons_per_chunk: 100000  # Larger chunks acceptable for sparse areas
enable_chunking: true

# Quality Thresholds (adjusted for sparse rangeland)
min_coverage_threshold: 0.7   # Lower coverage acceptable for extensive rangeland
min_density_threshold: 0.0005 # Very low threshold for sparse rangeland systems