# Rotterdam Study Area for Aerial Imagery Demo
# Focuses on port and urban interface for testing PDOK + DINOv3

name: rotterdam_aerial
description: "Rotterdam metropolitan area for aerial imagery testing"
country: netherlands
bioregion: north_sea_delta

# Geographic boundaries
boundaries:
  bbox: [4.2, 51.8, 4.6, 52.0]  # Rough Rotterdam area
  center: [4.4, 51.9]
  buffer_km: 5

# Coordinate systems
crs:
  input: "EPSG:4326"    # WGS84 for boundaries
  processing: "EPSG:28992"  # Dutch RD New for PDOK

# H3 resolutions for different analysis scales
h3_resolutions:
  overview: 8      # Regional scale (~0.7 km²)
  neighborhood: 9  # Neighborhood scale (~0.1 km²)
  block: 10       # Block scale (~0.01 km²)
  detailed: 11    # Building scale (~0.001 km²)
  fine: 12        # Fine scale for image fetching

# Modality configurations
modalities:
  aerial_imagery:
    enabled: true
    pdok_year: "current"
    model_name: "dinov3_rs_base"
    target_resolution: 10
    fine_resolution: 12
    hierarchical_levels: 2
    image_resolution: 512
    batch_size: 6
    rate_limit: 0.15  # Be gentle with PDOK
    
  alphaearth:
    enabled: true
    source_collection: "GOOGLE/RESEARCH/OPEN-BUILDINGS/V3/POLYGONS"
    years: [2021, 2023]
    resolution: 10
    
  poi:
    enabled: true
    categories: ["amenity", "shop", "leisure", "tourism", "office"]
    radius_m: 1000
    
  roads:
    enabled: true
    highway_types: ["primary", "secondary", "tertiary", "residential"]
    
  buildings:
    enabled: false  # Skip for this demo

# Analysis focus areas within Rotterdam
focus_areas:
  port:
    description: "Rotterdam port area"
    bbox: [4.1, 51.85, 4.3, 51.95]
    priority: "high"
    
  city_center:
    description: "Rotterdam city center"
    bbox: [4.45, 51.91, 4.50, 51.93]
    priority: "high"
    
  residential:
    description: "Residential neighborhoods"
    bbox: [4.48, 51.88, 4.55, 51.95]
    priority: "medium"

# Processing parameters
processing:
  chunk_size: 100
  max_workers: 4
  memory_limit_gb: 8
  
# Output configuration  
output:
  format: "parquet"
  compression: "snappy"
  include_metadata: true