# Klamath Basin Watershed Study Area
# Cross-border water management and agricultural sustainability

name: klamath_watershed
description: >
  Klamath Basin watershed spanning Oregon-California border region.
  Focus on integrated water management, drought resilience, agricultural 
  water use efficiency, and ecosystem restoration for sustainable food systems.

# Geographic Bounds Configuration
geographic_bounds:
  bounds_type: bbox
  definition:
    north: 43.2   # Upper Klamath Lake region
    south: 41.8   # Lower Klamath area (includes parts of Siskiyou County, CA)
    west: -122.8  # Western edge of basin
    east: -121.2  # Eastern edge in Oregon
  buffer_km: 5.0  # Larger buffer for watershed analysis
  crs: EPSG:4326

# Bioregional Context  
bioregional_context:
  bioregion_type: watershed
  primary_ecosystem: mixed_use
  management_focus:
    - water
    - crops  
    - biodiversity
    - drought_resilience
  climate_zone: semi_arid
  conservation_priority: high
  
  # Agricultural characteristics
  primary_crops:
    - alfalfa
    - potatoes
    - barley
    - pasture
  farming_type: conventional  # Though transitioning to more sustainable practices
  water_source: irrigated  # Heavy reliance on irrigation
  
  # Mixed forest-agriculture landscape
  forest_type: mixed
  timber_management: conservation  # Limited timber, focus on watershed protection

# Resolution Rules (water management and agricultural intensity-based)
resolution_rules:
  - name: irrigated_intensive_agriculture
    condition: "FSI_24 >= 0.15"
    resolution: 10
    priority: 100
    description: "Intensive irrigated agriculture requiring detailed water monitoring"
    
  - name: water_infrastructure
    condition: "building_volume >= 1000 and FSI_24 >= 0.05"
    resolution: 10
    priority: 95
    description: "Irrigation infrastructure, canals, and water management facilities"
    
  - name: riparian_wetland_zones
    condition: "FSI_24 < 0.03 and building_volume < 200"
    resolution: 10
    priority: 90
    description: "Riparian zones, wetlands, and stream corridors"
    
  - name: extensive_rangeland
    condition: "FSI_24 >= 0.01 and FSI_24 < 0.1"
    resolution: 9
    priority: 85
    description: "Rangeland and extensive agricultural areas"
    
  - name: forest_watershed_protection
    condition: "FSI_24 < 0.01 and building_volume < 100"
    resolution: 8
    priority: 80
    description: "Forest areas for watershed protection"
    
  - name: drought_vulnerable_areas
    condition: "FSI_24 >= 0.05 and FSI_24 < 0.15"
    resolution: 9
    priority: 88
    description: "Agricultural areas vulnerable to drought stress"

# Default resolution
default_resolution: 8

# Density Filtering Configuration  
density_filtering:
  enable: true
  method: fsi_threshold
  min_fsi_threshold: 0.003  # Include sparse rangeland and forest
  exclude_water_bodies: false  # Water features critical for watershed analysis
  focus_on_irrigated_areas: true

# Bioregional Filtering Configuration
bioregional_filtering:
  enable_ecosystem_rules: true
  prioritize_water_features: true
  include_riparian_buffers: true
  riparian_buffer_meters: 300  # Wide buffers for watershed management
  
  # Watershed-specific filtering
  irrigation_infrastructure_priority: high
  drought_monitoring_zones: true
  water_quality_monitoring: true
  agricultural_water_efficiency_focus: true

# Computational Constraints
max_memory_gb: 15.0
max_hexagons_per_chunk: 45000
enable_chunking: true

# Quality Thresholds
min_coverage_threshold: 0.88  # High coverage for water management
min_density_threshold: 0.003  # Include sparse rangeland for complete watershed view