version: 1
learning_rate: 0.3
min_observations: 2
segments:
  sunday-morning:
    observations: 3
    first_seen: '2026-03-13T15:29:33.386589+00:00'
    last_seen: '2026-03-13T15:29:33.413554+00:00'
    prior:
      mode: sprint
      dimensions:
        execution_speed: 4.02
        exploration_vs_exploitation: 3.98
        code_quality: 3.51
        test_coverage: 3.0199999999999996
        spatial_correctness: 3.0199999999999996
        model_architecture: 3.53
        urgency: 3.0
    mode_history:
    - focused
    - sprint
    - sprint
  sunday-afternoon:
    observations: 1
    first_seen: '2026-03-13T15:29:33.392063+00:00'
    last_seen: '2026-03-13T15:29:33.392063+00:00'
    prior:
      mode: sprint
      dimensions:
        execution_speed: 5.0
        exploration_vs_exploitation: 4.0
        code_quality: 3.0
        test_coverage: 2.0
        spatial_correctness: 2.0
        model_architecture: 2.0
        urgency: 5.0
    mode_history:
    - sprint
  friday-evening:
    observations: 2
    first_seen: '2026-03-13T15:29:33.407160+00:00'
    last_seen: '2026-03-13T15:29:33.419506+00:00'
    prior:
      mode: focused
      dimensions:
        execution_speed: 3.3
        exploration_vs_exploitation: 3.4
        code_quality: 2.9999999999999996
        test_coverage: 2.6999999999999997
        spatial_correctness: 2.9999999999999996
        model_architecture: 4.3
    mode_history:
    - focused
    - focused
  saturday-morning:
    observations: 3
    first_seen: '2026-03-14T10:00:17.591199+00:00'
    last_seen: '2026-03-14T10:00:46.240261+00:00'
    prior:
      mode: focused
      dimensions:
        execution_speed: 4.0
        exploration_vs_exploitation: 4.0
        code_quality: 4.0
        test_coverage: 2.0
        spatial_correctness: 2.0
        model_architecture: 4.0
        urgency: 2.0
        data_engineering_diligence: 4.0
    mode_history:
    - focused
    - focused
    - focused
