# Cascadia Coastal Forest Analysis Configuration
# Focus: 2021 AlphaEarth data for forested coastal band west of -121°
# Processing mode: Modular tile-based with checkpointing using SRAI

experiment:
  name: cascadia_coastal_forests_2021
  year: 2021
  h3_resolution: 8  # Resolution 8 for regional analysis
  keep_dimensions: 64  # Full AlphaEarth embeddings
  max_tiles: null  # Process ALL available tiles in study area
  processing_mode: modular  # Use modular processor with checkpointing

# Study area: Coastal forested band (excludes eastern prairies/valleys)
study_area:
  name: "Cascadia Coastal Forests"
  description: "Forested coastal band west of -121° - Coast Range, Klamath Mountains, coastal forests"
  ecological_zones: ["Coast Range", "Klamath Mountains", "Coastal Douglas-fir", "Coastal Redwood"]
  bounds:
    west: -124.703589    # Pacific Coast
    east: -121.000000    # Exclude eastern prairies/valleys
    south: 38.667442     # Northern California
    north: 43.372548     # Southern Oregon
  area_sq_km: ~185000     # Reduced from full 426k sq km
  estimated_hexagons: ~105000  # At H3 resolution 8, much more manageable
  tiles_in_area: ~612         # Out of 968 total tiles (63% coverage)
  
data:
  source_dir: "G:/My Drive/AlphaEarth_Cascadia"
  pattern: "Cascadia_AlphaEarth_2021_*.tif"
  output_file: "del_norte_2021_res8_full.parquet"
  h3_resolution: 8  # Updated to resolution 8
  
  # AlphaEarth specifications
  bands: 64  # A00 through A63
  tile_size: 3072  # pixels
  pixel_resolution: 10  # meters
  crs: "EPSG:4326"
  
  # Del Norte approximate bounds (for reference)
  del_norte_bounds:
    north: 42.0
    south: 41.5
    west: -124.4
    east: -123.8

processing:
  # Modular processing embeddings parameters
  subtile_size: 256  # Process TIFF in 256x256 pixel chunks
  subtiles_per_batch: 10  # Process 10 subtiles before checkpointing
  aggregation_method: "mean"  # How to aggregate pixels to H3
  min_pixels_per_hex: 5  # Minimum valid pixels for hexagon inclusion
  
  # Enhanced boundary handling
  boundary_buffer_pixels: 32  # Overlap buffer between tiles (pixels)
  edge_sampling_density: 2    # Sampling density multiplier near tile edges
  track_coverage: true        # Track pixel coverage quality for each hexagon
  
  # H3 specific
  h3_resolution: 8
  sampling_stride: 10  # Sample every 10th coordinate for H3 generation
  
  # Memory management
  use_sparse: false  # Keep dense for 64-dim data
  chunk_size: 256  # Subtile size for modular processing embeddings
  memory_cleanup_interval: 5  # Run gc.collect() every N tiles
  
  # Checkpointing
  checkpoint_enabled: true
  checkpoint_dir: "data/checkpoints"
  resume_from_checkpoint: true  # Automatically resume if checkpoint exists
  cleanup_intermediates: false  # Keep intermediate files for debugging
  
clustering:
  # K-means configurations
  kmeans:
    n_clusters: [5, 10, 15, 20]
    n_init: 10
    max_iter: 300
    random_state: 42
    
  # Hierarchical clustering
  hierarchical:
    n_clusters: [8, 12, 16]
    linkage: ["ward", "complete", "average"]
    
  # Gaussian Mixture Models
  gmm:
    n_components: [5, 10, 15]
    covariance_type: "full"
    max_iter: 100
    random_state: 42
    
visualization:
  # Categorical color schemes for cluster maps
  colormaps:
    - "tab10"      # Best for up to 10 clusters
    - "tab20"      # For 11-20 clusters
    - "Set1"       # Bright categorical colors
    - "Set2"       # Pastel categorical colors
    - "Set3"       # More categorical colors
    - "Paired"     # Paired categorical colors
    - "Accent"     # Accent categorical colors
    
  # Plot settings
  figure_size: [15, 10]
  dpi: 150
  hex_size: 0.8  # Size multiplier for hexagons
  
  # Save formats
  save_formats: ["png", "pdf"]
  
output:
  # File naming pattern
  naming_pattern: "{method}_2021_res8_{detail}"
  
  # Results structure
  results_dir: "results"
  plots_dir: "plots"
  cache_dir: "data/cache"
  
  # Modular processing embeddings outputs
  modular_dir: "data/h3_2021_res8_coastal_forests"
  intermediate_dir: "data/intermediate"  # Store subtile results
  archive_dir: "data/archive"  # For completed runs
  
  # Logging
  log_level: "INFO"
  log_file: "logs/modular_processing.log"
  progress_log: "logs/progress.json"  # JSON progress tracking
  
performance:
  # Parallel processing embeddings
  n_jobs: -1  # Use all cores
  
  # Caching
  enable_cache: true
  cache_embeddings: true
  cache_clusters: true
  
  # Progress reporting
  verbose: true
  show_progress: true

# Rioxarray optimization settings
rioxarray:
  # Memory management
  chunk_size_mb: 100  # Target chunk size in MB
  use_parallel: true  # Enable parallel processing embeddings
  optimize_chunks: true  # Optimize chunk sizes automatically
  
  # Performance tuning
  lock: false  # Disable locking for COG files
  decode_times: false  # Skip time decoding for speed
  export_grid_mapping: false  # Disable grid mapping export

# SRAI settings for optimized H3 operations
srai:
  # H3 regionalization
  use_vectorized: true  # Use vectorized H3 operations
  cache_regionalizer: true  # Cache H3 regionalizer between tiles
  
  # Spatial operations
  use_neighbourhood: true  # Use H3Neighbourhood for spatial relationships
  parallel_h3_conversion: true  # Process H3 conversions in parallel
  
  # Integration with rioxarray
  combined_processing: true  # Use SRAI+rioxarray optimization
  adaptive_sampling: true  # Adjust sampling based on resolution

# Spatial smoothing configuration for boundary gap elimination
smoothing:
  # Geographic continuity parameters
  boundary_buffer_km: 2.0      # Buffer distance for boundary detection
  smoothing_radius_km: 1.5     # Radius for spatial smoothing operations
  min_neighbors: 3             # Minimum neighbors required for smoothing
  coverage_threshold: 0.5      # Minimum coverage quality for hexagon inclusion
  smoothing_strength: 0.3      # Blending strength (0=no smoothing, 1=full smoothing)
  
  # Gap filling parameters  
  enable_interpolation: true   # Fill gaps using spatial interpolation
  interpolation_method: "idw" # Inverse distance weighting
  max_interpolation_distance_km: 3.0  # Max distance for gap filling
  
  # Quality validation
  validate_continuity: true    # Run spatial continuity validation
  continuity_threshold: 0.7    # Minimum continuity score for acceptance
  boundary_smoothness_weight: 0.4  # Weight for boundary smoothness in quality score

# Hardware optimization settings (RTX 3090 + 12-core CPU + NVMe SSD)
hardware:
  # CPU settings
  max_cores: 12  # Use all 12 physical cores
  parallel_tiles: true  # Process multiple tiles simultaneously
  
  # GPU settings
  use_gpu: true  # Enable RTX 3090 GPU acceleration
  gpu_memory_gb: 20  # Reserve 20GB of 24GB VRAM
  gpu_chunk_size: 2048  # Doubled chunk size for better GPU utilization
  
  # Memory management
  prefetch_tiles: 5  # Increased prefetch for full dataset processing embeddings
  memory_pool_gb: 16  # System memory pool
  pinned_memory: true  # Use pinned memory for faster GPU transfers
  
  # I/O optimization for NVMe SSD
  async_io: true  # Asynchronous file operations
  io_threads: 4  # Dedicated I/O threads
  read_ahead_mb: 1024  # Increased SSD read-ahead buffer
  
  # Mixed precision settings
  use_mixed_precision: true  # Enable FP16 for 2x memory efficiency
  tf32_enabled: true  # Use TensorFloat-32 on RTX 3090
  
  # Enhanced processing embeddings for boundary gap elimination
  enable_boundary_optimization: true  # Use enhanced boundary processing embeddings
  spatial_smoothing_enabled: true     # Apply spatial smoothing in stitching